# Cloudflare Pages — wrangler.toml
# Place this file in the root of your project.

name = "cozier"
pages_build_output_dir = "."
compatibility_date = "2024-04-01"

[[kv_namespaces]]
binding = "COZIER"
id = "3f9d6e1a70c1488e83eef88ba148ad8e"

